apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: steep-warbler-python 
  janus-idp.io/tekton: steep-warbler-python
  backstage.io/kubernetes-id: steep-warbler-python
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: steep-warbler-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  