apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: steep-warbler-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: steep-warbler-python 
  name: steep-warbler-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: steep-warbler-python 
